@echo off
set "root=app\src\main\res\layout"
set "base=app\src\main\res\layouts"

:: Create directories (already done, but just in case)
mkdir "%base%\auth\layout" 2>nul
mkdir "%base%\student\layout" 2>nul
mkdir "%base%\supplier\layout" 2>nul
mkdir "%base%\property\layout" 2>nul
mkdir "%base%\chat\layout" 2>nul
mkdir "%base%\billing\layout" 2>nul
mkdir "%base%\admin\layout" 2>nul
mkdir "%base%\caretaker\layout" 2>nul
mkdir "%base%\other\layout" 2>nul

echo Moving layouts to domain folders...

:: Auth
move "%root%\activity_login.xml" "%base%\auth\layout\"
move "%root%\activity_phone_auth.xml" "%base%\auth\layout\"
move "%root%\activity_private_access.xml" "%base%\auth\layout\"
move "%root%\sign_up.xml" "%base%\auth\layout\"

:: Student
move "%root%\activity_student_dashboard.xml" "%base%\student\layout\"
move "%root%\activity_student_edit_profile.xml" "%base%\student\layout\"
move "%root%\activity_student_profile.xml" "%base%\student\layout\"
move "%root%\activity_favorites.xml" "%base%\student\layout\"
move "%root%\item_student.xml" "%base%\student\layout\"
move "%root%\item_cart.xml" "%base%\student\layout\"
move "%root%\activity_edit_profile_v8.xml" "%base%\student\layout\"

:: Supplier
move "%root%\activity_add_water_service.xml" "%base%\supplier\layout\"
move "%root%\activity_water_supplier_dashboard.xml" "%base%\supplier\layout\"
move "%root%\activity_water_supplier_notifications.xml" "%base%\supplier\layout\"
move "%root%\activity_water_supplier_profile.xml" "%base%\supplier\layout\"
move "%root%\activity_water_suppliers.xml" "%base%\supplier\layout\"
move "%root%\activity_supplier_orders.xml" "%base%\supplier\layout\"
move "%root%\item_water_supplier.xml" "%base%\supplier\layout\"
move "%root%\item_supplier_order.xml" "%base%\supplier\layout\"

:: Chat
move "%root%\activity_chat.xml" "%base%\chat\layout\"
move "%root%\activity_chat_list.xml" "%base%\chat\layout\"
move "%root%\item_chat_room.xml" "%base%\chat\layout\"
move "%root%\item_message.xml" "%base%\chat\layout\"
move "%root%\item_message_thread.xml" "%base%\chat\layout\"
move "%root%\item_ms_received.xml" "%base%\chat\layout\"
move "%root%\item_ms_received_reply.xml" "%base%\chat\layout\"
move "%root%\item_ms_sent.xml" "%base%\chat\layout\"
move "%root%\item_ms_sent_reply.xml" "%base%\chat\layout\"
move "%root%\item_ms_system.xml" "%base%\chat\layout\"

:: Billing
move "%root%\activity_booking_details.xml" "%base%\billing\layout\"
move "%root%\activity_my_bookings.xml" "%base%\billing\layout\"
move "%root%\activity_payment_details.xml" "%base%\billing\layout\"
move "%root%\activity_rent_tracking.xml" "%base%\billing\layout\"
move "%root%\item_booking.xml" "%base%\billing\layout\"
move "%root%\layout_mpesa_payment.xml" "%base%\billing\layout\"

:: Admin
move "%root%\activity_admin_dashboard.xml" "%base%\admin\layout\"
move "%root%\activity_admin_notifications.xml" "%base%\admin\layout\"
move "%root%\activity_admin_profile.xml" "%base%\admin\layout\"
move "%root%\activity_analytics.xml" "%base%\admin\layout\"
move "%root%\activity_application_details_v8.xml" "%base%\admin\layout\"
move "%root%\activity_caretaker_details.xml" "%base%\admin\layout\"
move "%root%\activity_manage_applications.xml" "%base%\admin\layout\"
move "%root%\activity_manage_caretakers.xml" "%base%\admin\layout\"
move "%root%\activity_manage_properties.xml" "%base%\admin\layout\"
move "%root%\activity_manage_students.xml" "%base%\admin\layout\"
move "%root%\activity_suspended_users.xml" "%base%\admin\layout\"
move "%root%\activity_verified_users.xml" "%base%\admin\layout\"
move "%root%\activity_performance_v8.xml" "%base%\admin\layout\"
move "%root%\activity_manage_users.xml" "%base%\admin\layout\"
move "%root%\activity_id_verification.xml" "%base%\admin\layout\"
move "%root%\activity_reports.xml" "%base%\admin\layout\"
move "%root%\fragment_admin_profile.xml" "%base%\admin\layout\"
move "%root%\item_admin.xml" "%base%\admin\layout\"
move "%root%\item_admin_property.xml" "%base%\admin\layout\"
move "%root%\item_recent_activity.xml" "%base%\admin\layout\"
move "%root%\item_application.xml" "%base%\admin\layout\"
move "%root%\item_caretaker.xml" "%base%\admin\layout\"
move "%root%\item_tenant_risk.xml" "%base%\admin\layout\"
move "%root%\item_analytics_booking.xml" "%base%\admin\layout\"
move "%root%\item_analytics_booking_modern.xml" "%base%\admin\layout\"
move "%root%\item_analytics_insight.xml" "%base%\admin\layout\"
move "%root%\item_analytics_insight_modern.xml" "%base%\admin\layout\"
move "%root%\dialog_add_caretaker.xml" "%base%\admin\layout\"
move "%root%\dialog_add_student_admin.xml" "%base%\admin\layout\"
move "%root%\dialog_caretaker_verification.xml" "%base%\admin\layout\"
move "%root%\dialog_add_note.xml" "%base%\admin\layout\"
move "%root%\view_analytics_bar.xml" "%base%\admin\layout\"
move "%root%\view_analytics_bar_modern.xml" "%base%\admin\layout\"

:: Caretaker
move "%root%\activity_caretaker_application.xml" "%base%\caretaker\layout\"
move "%root%\activity_caretaker_dashboard.xml" "%base%\caretaker\layout\"
move "%root%\activity_caretaker_messages.xml" "%base%\caretaker\layout\"
move "%root%\activity_caretaker_notifications.xml" "%base%\caretaker\layout\"
move "%root%\activity_caretaker_profile.xml" "%base%\caretaker\layout\"
move "%root%\activity_my_properties.xml" "%base%\caretaker\layout\"
move "%root%\fragment_caretaker_requests.xml" "%base%\caretaker\layout\"
move "%root%\fragment_host_requests.xml" "%base%\caretaker\layout\"
move "%root%\item_caretaker_properties.xml" "%base%\caretaker\layout\"
move "%root%\item_caretaker_request.xml" "%base%\caretaker\layout\"
move "%root%\item_my_property.xml" "%base%\caretaker\layout\"
move "%root%\item_host_properties.xml" "%base%\caretaker\layout\"
move "%root%\item_host_property.xml" "%base%\caretaker\layout\"

:: Property
move "%root%\activity_add_property.xml" "%base%\property\layout\"
move "%root%\activity_all_properties.xml" "%base%\property\layout\"
move "%root%\activity_all_property.xml" "%base%\property\layout\"
move "%root%\activity_filter_v8.xml" "%base%\property\layout\"
move "%root%\activity_property_details.xml" "%base%\property\layout\"
move "%root%\activity_reviews.xml" "%base%\property\layout\"
move "%root%\activity_room_manager.xml" "%base%\property\layout\"
move "%root%\fragment_properties.xml" "%base%\property\layout\"
move "%root%\item_property.xml" "%base%\property\layout\"
move "%root%\item_property1.xml" "%base%\property\layout\"
move "%root%\item_property_image.xml" "%base%\property\layout\"
move "%root%\item_property_image_detail.xml" "%base%\property\layout\"
move "%root%\item_property_image_preview.xml" "%base%\property\layout\"
move "%root%\item_property_modern.xml" "%base%\property\layout\"
move "%root%\item_property_performance.xml" "%base%\property\layout\"
move "%root%\item_property_vertical.xml" "%base%\property\layout\"
move "%root%\item_house_grid.xml" "%base%\property\layout\"
move "%root%\item_house_horizontal.xml" "%base%\property\layout\"
move "%root%\item_house_vertical.xml" "%base%\property\layout\"
move "%root%\item_room_management.xml" "%base%\property\layout\"
move "%root%\item_room_selection.xml" "%base%\property\layout\"
move "%root%\item_room_type_edit.xml" "%base%\property\layout\"
move "%root%\item_amenity.xml" "%base%\property\layout\"
move "%root%\item_amenity_display.xml" "%base%\property\layout\"
move "%root%\item_amenity_simple.xml" "%base%\property\layout\"
move "%root%\item_feature.xml" "%base%\property\layout\"
move "%root%\item_category.xml" "%base%\property\layout\"
move "%root%\item_image_slider.xml" "%base%\property\layout\"
move "%root%\item_room_image.xml" "%base%\property\layout\"
move "%root%\item_room_images.xml" "%base%\property\layout\"
move "%root%\item_review.xml" "%base%\property\layout\"
move "%root%\dialog_add_room.xml" "%base%\property\layout\"
move "%root%\dialog_add_room_type.xml" "%base%\property\layout\"
move "%root%\dialog_reviews.xml" "%base%\property\layout\"
move "%root%\reviews_dialog.xml" "%base%\property\layout\"
move "%root%\view_rating_bar_row.xml" "%base%\property\layout\"
move "%root%\view_review_info_row_v8.xml" "%base%\property\layout\"

:: Other
move "%root%\activity_main.xml" "%base%\other\layout\"
move "%root%\activity_splash.xml" "%base%\other\layout\"
move "%root%\activity_settings.xml" "%base%\other\layout\"
move "%root%\activity_notifications.xml" "%base%\other\layout\"
move "%root%\activity_maintenance.xml" "%base%\other\layout\"
move "%root%\activity_image_viewer.xml" "%base%\other\layout\"
move "%root%\activity_location_details.xml" "%base%\other\layout\"
move "%root%\activity_map_location_picker.xml" "%base%\other\layout\"
move "%root%\activity_role_selection.xml" "%base%\other\layout\"
move "%root%\activity_user_edit_profile.xml" "%base%\other\layout\"
move "%root%\item_notifications.xml" "%base%\other\layout\"
move "%root%\layout_document_verification_bottom_sheet.xml" "%base%\other\layout\"
move "%root%\layout_name_confirmation.xml" "%base%\other\layout\"
move "%root%\layout_profile_item.xml" "%base%\other\layout\"
move "%root%\layout_profile_item_modern.xml" "%base%\other\layout\"
move "%root%\layout_section_header.xml" "%base%\other\layout\"
move "%root%\bg_header_rounded_bottom.xml" "%base%\other\layout\"
move "%root%\dialog_fullscreen_image.xml" "%base%\other\layout\"
move "%root%\dialog_location_summary.xml" "%base%\other\layout\"
move "%root%\dialog_phone_numbers.xml" "%base%\other\layout\"
move "%root%\dialog_qr_code.xml" "%base%\other\layout\"
move "%root%\dialog_set_password.xml" "%base%\other\layout\"
move "%root%\spinner_dropdown_item.xml" "%base%\other\layout\"
move "%root%\spinner_item.xml" "%base%\other\layout\"
move "%root%\test_notification_button.xml" "%base%\other\layout\"

echo Reorganization complete!
pause
